//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Klient.Service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddExponatOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddRoomOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddMigratOperationCompleted;
        
        private System.Threading.SendOrPostCallback DelExponatOperationCompleted;
        
        private System.Threading.SendOrPostCallback DelRoomOperationCompleted;
        
        private System.Threading.SendOrPostCallback DelMigratOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetExponatsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRoomsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMigratsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::Klient.Properties.Settings.Default.Klient_Service_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddExponatCompletedEventHandler AddExponatCompleted;
        
        /// <remarks/>
        public event AddRoomCompletedEventHandler AddRoomCompleted;
        
        /// <remarks/>
        public event AddMigratCompletedEventHandler AddMigratCompleted;
        
        /// <remarks/>
        public event DelExponatCompletedEventHandler DelExponatCompleted;
        
        /// <remarks/>
        public event DelRoomCompletedEventHandler DelRoomCompleted;
        
        /// <remarks/>
        public event DelMigratCompletedEventHandler DelMigratCompleted;
        
        /// <remarks/>
        public event GetExponatsCompletedEventHandler GetExponatsCompleted;
        
        /// <remarks/>
        public event GetRoomsCompletedEventHandler GetRoomsCompleted;
        
        /// <remarks/>
        public event GetMigratsCompletedEventHandler GetMigratsCompleted;
        
        /// <remarks/>
        public event AuthCompletedEventHandler AuthCompleted;
        
        /// <remarks/>
        public event RegisterCompletedEventHandler RegisterCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddExponat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddExponat(string name) {
            this.Invoke("AddExponat", new object[] {
                        name});
        }
        
        /// <remarks/>
        public void AddExponatAsync(string name) {
            this.AddExponatAsync(name, null);
        }
        
        /// <remarks/>
        public void AddExponatAsync(string name, object userState) {
            if ((this.AddExponatOperationCompleted == null)) {
                this.AddExponatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddExponatOperationCompleted);
            }
            this.InvokeAsync("AddExponat", new object[] {
                        name}, this.AddExponatOperationCompleted, userState);
        }
        
        private void OnAddExponatOperationCompleted(object arg) {
            if ((this.AddExponatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddExponatCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddRoom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddRoom(string name) {
            this.Invoke("AddRoom", new object[] {
                        name});
        }
        
        /// <remarks/>
        public void AddRoomAsync(string name) {
            this.AddRoomAsync(name, null);
        }
        
        /// <remarks/>
        public void AddRoomAsync(string name, object userState) {
            if ((this.AddRoomOperationCompleted == null)) {
                this.AddRoomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddRoomOperationCompleted);
            }
            this.InvokeAsync("AddRoom", new object[] {
                        name}, this.AddRoomOperationCompleted, userState);
        }
        
        private void OnAddRoomOperationCompleted(object arg) {
            if ((this.AddRoomCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddRoomCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddMigrat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddMigrat(System.DateTime date, int exponat, int room) {
            this.Invoke("AddMigrat", new object[] {
                        date,
                        exponat,
                        room});
        }
        
        /// <remarks/>
        public void AddMigratAsync(System.DateTime date, int exponat, int room) {
            this.AddMigratAsync(date, exponat, room, null);
        }
        
        /// <remarks/>
        public void AddMigratAsync(System.DateTime date, int exponat, int room, object userState) {
            if ((this.AddMigratOperationCompleted == null)) {
                this.AddMigratOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddMigratOperationCompleted);
            }
            this.InvokeAsync("AddMigrat", new object[] {
                        date,
                        exponat,
                        room}, this.AddMigratOperationCompleted, userState);
        }
        
        private void OnAddMigratOperationCompleted(object arg) {
            if ((this.AddMigratCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddMigratCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DelExponat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DelExponat(int id) {
            this.Invoke("DelExponat", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void DelExponatAsync(int id) {
            this.DelExponatAsync(id, null);
        }
        
        /// <remarks/>
        public void DelExponatAsync(int id, object userState) {
            if ((this.DelExponatOperationCompleted == null)) {
                this.DelExponatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelExponatOperationCompleted);
            }
            this.InvokeAsync("DelExponat", new object[] {
                        id}, this.DelExponatOperationCompleted, userState);
        }
        
        private void OnDelExponatOperationCompleted(object arg) {
            if ((this.DelExponatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DelExponatCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DelRoom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DelRoom(int id) {
            this.Invoke("DelRoom", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void DelRoomAsync(int id) {
            this.DelRoomAsync(id, null);
        }
        
        /// <remarks/>
        public void DelRoomAsync(int id, object userState) {
            if ((this.DelRoomOperationCompleted == null)) {
                this.DelRoomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelRoomOperationCompleted);
            }
            this.InvokeAsync("DelRoom", new object[] {
                        id}, this.DelRoomOperationCompleted, userState);
        }
        
        private void OnDelRoomOperationCompleted(object arg) {
            if ((this.DelRoomCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DelRoomCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DelMigrat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DelMigrat(int id) {
            this.Invoke("DelMigrat", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void DelMigratAsync(int id) {
            this.DelMigratAsync(id, null);
        }
        
        /// <remarks/>
        public void DelMigratAsync(int id, object userState) {
            if ((this.DelMigratOperationCompleted == null)) {
                this.DelMigratOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelMigratOperationCompleted);
            }
            this.InvokeAsync("DelMigrat", new object[] {
                        id}, this.DelMigratOperationCompleted, userState);
        }
        
        private void OnDelMigratOperationCompleted(object arg) {
            if ((this.DelMigratCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DelMigratCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetExponats", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Exponat[] GetExponats() {
            object[] results = this.Invoke("GetExponats", new object[0]);
            return ((Exponat[])(results[0]));
        }
        
        /// <remarks/>
        public void GetExponatsAsync() {
            this.GetExponatsAsync(null);
        }
        
        /// <remarks/>
        public void GetExponatsAsync(object userState) {
            if ((this.GetExponatsOperationCompleted == null)) {
                this.GetExponatsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetExponatsOperationCompleted);
            }
            this.InvokeAsync("GetExponats", new object[0], this.GetExponatsOperationCompleted, userState);
        }
        
        private void OnGetExponatsOperationCompleted(object arg) {
            if ((this.GetExponatsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetExponatsCompleted(this, new GetExponatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRooms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Room[] GetRooms() {
            object[] results = this.Invoke("GetRooms", new object[0]);
            return ((Room[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRoomsAsync() {
            this.GetRoomsAsync(null);
        }
        
        /// <remarks/>
        public void GetRoomsAsync(object userState) {
            if ((this.GetRoomsOperationCompleted == null)) {
                this.GetRoomsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRoomsOperationCompleted);
            }
            this.InvokeAsync("GetRooms", new object[0], this.GetRoomsOperationCompleted, userState);
        }
        
        private void OnGetRoomsOperationCompleted(object arg) {
            if ((this.GetRoomsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRoomsCompleted(this, new GetRoomsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMigrats", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Migrat[] GetMigrats() {
            object[] results = this.Invoke("GetMigrats", new object[0]);
            return ((Migrat[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMigratsAsync() {
            this.GetMigratsAsync(null);
        }
        
        /// <remarks/>
        public void GetMigratsAsync(object userState) {
            if ((this.GetMigratsOperationCompleted == null)) {
                this.GetMigratsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMigratsOperationCompleted);
            }
            this.InvokeAsync("GetMigrats", new object[0], this.GetMigratsOperationCompleted, userState);
        }
        
        private void OnGetMigratsOperationCompleted(object arg) {
            if ((this.GetMigratsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMigratsCompleted(this, new GetMigratsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Auth", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Auth(string name, string password) {
            object[] results = this.Invoke("Auth", new object[] {
                        name,
                        password});
            return ((System.Nullable<int>)(results[0]));
        }
        
        /// <remarks/>
        public void AuthAsync(string name, string password) {
            this.AuthAsync(name, password, null);
        }
        
        /// <remarks/>
        public void AuthAsync(string name, string password, object userState) {
            if ((this.AuthOperationCompleted == null)) {
                this.AuthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthOperationCompleted);
            }
            this.InvokeAsync("Auth", new object[] {
                        name,
                        password}, this.AuthOperationCompleted, userState);
        }
        
        private void OnAuthOperationCompleted(object arg) {
            if ((this.AuthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthCompleted(this, new AuthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Register", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Register(string name, string password) {
            this.Invoke("Register", new object[] {
                        name,
                        password});
        }
        
        /// <remarks/>
        public void RegisterAsync(string name, string password) {
            this.RegisterAsync(name, password, null);
        }
        
        /// <remarks/>
        public void RegisterAsync(string name, string password, object userState) {
            if ((this.RegisterOperationCompleted == null)) {
                this.RegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterOperationCompleted);
            }
            this.InvokeAsync("Register", new object[] {
                        name,
                        password}, this.RegisterOperationCompleted, userState);
        }
        
        private void OnRegisterOperationCompleted(object arg) {
            if ((this.RegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Exponat {
        
        private int idField;
        
        private string nameField;
        
        private Migrat[] migratField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public Migrat[] Migrat {
            get {
                return this.migratField;
            }
            set {
                this.migratField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Migrat {
        
        private int idField;
        
        private int roomIdField;
        
        private int exponatIdField;
        
        private System.DateTime date1Field;
        
        private Room roomField;
        
        private Exponat exponatField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int RoomId {
            get {
                return this.roomIdField;
            }
            set {
                this.roomIdField = value;
            }
        }
        
        /// <remarks/>
        public int ExponatId {
            get {
                return this.exponatIdField;
            }
            set {
                this.exponatIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Date1 {
            get {
                return this.date1Field;
            }
            set {
                this.date1Field = value;
            }
        }
        
        /// <remarks/>
        public Room Room {
            get {
                return this.roomField;
            }
            set {
                this.roomField = value;
            }
        }
        
        /// <remarks/>
        public Exponat Exponat {
            get {
                return this.exponatField;
            }
            set {
                this.exponatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Room {
        
        private int idField;
        
        private string nameField;
        
        private Migrat[] migratField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public Migrat[] Migrat {
            get {
                return this.migratField;
            }
            set {
                this.migratField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AddExponatCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AddRoomCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AddMigratCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DelExponatCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DelRoomCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DelMigratCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetExponatsCompletedEventHandler(object sender, GetExponatsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetExponatsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetExponatsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Exponat[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Exponat[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetRoomsCompletedEventHandler(object sender, GetRoomsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRoomsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRoomsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Room[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Room[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetMigratsCompletedEventHandler(object sender, GetMigratsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMigratsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMigratsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Migrat[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Migrat[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AuthCompletedEventHandler(object sender, AuthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Nullable<int> Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Nullable<int>)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RegisterCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591